---
sudo: required

language: cpp

os:
  - linux
compiler:
  - gcc
  - clang
env:
  - CONFIGURE_OPTIONS=--disable-shared
  - CONFIGURE_OPTIONS=
matrix:
  include:
    - os: linux
      compiler: gcc
      env: HOST=i386-pc-linux-gnu MEVAL='export CC="$CC -m32" && CXX="$CXX -m32"'
    - os: linux
      env: HOST=moxie-elf MEVAL='export PATH=/opt/moxielogic/bin:$PATH && LDFLAGS="-Tsim.ld" && RUNTESTFLAGS="--target_board moxie-sim" && DEJAGNU="$TRAVIS_BUILD_DIR"/.travis && CC=moxie-elf-gcc && CXX=moxie-elf-g++'

before_install:
  - if test x"$MEVAL" != x; then eval ${MEVAL}; fi

install:
  - ./.travis/install.sh

script:
  - echo $MEVAL
  - env
  - echo ------------------------------------------
  - if test x"$MEVAL" != x; then eval ${MEVAL}; fi
  - echo ------------------------------------------
  - if test x"$MEVAL" != x; then eval ${MEVAL}; fi
  - ./autogen.sh
  - ./configure ${HOST+--host=$HOST} ${CONFIGURE_OPTIONS}
  - make
  - make dist
  - make check
  - cat */testsuite/libffi.log
